---
- hosts: devmasters
  remote_user: root
  tasks:
    - name: Run apt-get upgrade
      apt:
        update_cache: 'yes'
        upgrade: 'yes'

    - name: Upgrade devshop-cli
      shell: devshop self-update -n
      args:
        chdir: /usr/share/devshop

    - name: Upgrade devshop
      shell: devshop upgrade -n
