---
- hosts: all
  remote_user: root
  tasks:

    - name: Add sysadmins to the system.
      user: 
        name: item.username
        shell: /bin/bash 
        groups: sudo 
        append: yes
      with_items: system_administrators | list

    - name: Add authorized keys for each user.
      authorized_key: 
        user: item.username
        key: item.keys
      with_items: system_administrators | list
